# Generated by Django 6.0.7 on 2026-07-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_event_t_95c293_idx',
            old_name='core_audit_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_2a1528_idx',
            old_name='core_audit_user_idx',
        ),
    ]
