# Generated by Django 6.0.7 on 2026-07-20 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-award', max_length=50)),
                ('trigger', models.CharField(choices=[('first_problem', 'First Problem'), ('first_accepted', 'First Accepted Solution'), ('top_contributor', 'Top Contributor'), ('mentor', 'Mentor'), ('rep_100', '100 Reputation'), ('rep_1000', '1000 Reputation'), ('connector', '10 Connections')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReputationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('solution_accepted', 'Solution Accepted'), ('solution_upvoted', 'Solution Upvoted'), ('solution_downvoted', 'Solution Downvoted'), ('problem_posted', 'Problem Posted'), ('comment_helpful', 'Comment Helpful'), ('opportunity_posted', 'Opportunity Posted'), ('connection_accepted', 'Connection Accepted'), ('upvote_removed', 'Upvote Removed'), ('content_deleted', 'Content Deleted'), ('spam_reported', 'Spam Reported')], db_index=True, max_length=30)),
                ('delta', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reputation__user_id_eb7035_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
