# Generated by Django 6.0.4 on 2026-04-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
