# Generated by Django 6.0.4 on 2026-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
