# Generated by Django 6.0.7 on 2026-07-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_684eac_idx',
            old_name='notif_recipient_read_idx',
        ),
    ]
